# site settings
title: Armin Geyer
subtitle: Garten und Hofpflege in Regenstauf und Umgebung
email: stefan.riembauer@gmail.com
description: Garten und Hofpflege in Regenstauf und Umgebung
baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://testing.hirnkastl.info" # the base hostname & protocol for your site
author: Armin Geyer
street_address: Regendorfer Str 57
city: Regenstauf
state:
zip_code: 93128
country: Deutschland
phone: 09402 7816952
pagination:
  enabled: true
  per_page: 4
  indexpage: blog
  sort_reverse: true

# social settings
500px_url:
facebook_url:
github_url:
gitlab_url:
googleplus_url:
instagram_url:
linkedin_url:
pinterest_url:
slack_url:
twitter_url:

# build settings
markdown: kramdown

sass:
  style: compressed

plugins:
  - jekyll-paginate-v2
